using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RuMC14.Ordnance;

[GenerateTypedNameReferences]
public sealed partial class RuMCExplosionSimulatorWindow : DefaultWindow
{
    public Action<FrameEventArgs>? OnFrameUpdate;

    public RuMCExplosionSimulatorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        OnFrameUpdate?.Invoke(args);
    }
}
