using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Ordnance;

[GenerateTypedNameReferences]
public sealed partial class RMCDemolitionsSimulatorWindow : DefaultWindow
{
    public RMCDemolitionsSimulatorWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
